/**
 * 管理面板页面
 *
 * 单文件 HTML，内嵌为字符串随 Worker 一起部署，不需要构建工具，
 * 也不依赖任何外部 CDN（避免 CSP 与离线环境的问题）。
 */

export function handleAdminUi(request, env, url) {
  return new Response(ADMIN_HTML, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-store',
      'X-Robots-Tag': 'noindex, nofollow',
    },
  });
}

// 用数组 join 而非模板字符串，这样内嵌的 JS 里可以自由使用反引号与 ${}
const ADMIN_HTML = [
'<!DOCTYPE html>',
'<html lang="zh-CN">',
'<head>',
'<meta charset="utf-8">',
'<meta name="viewport" content="width=device-width, initial-scale=1">',
'<meta name="robots" content="noindex, nofollow">',
'<title>cf-api-switch · 渠道管理</title>',
'<style>',
'* { box-sizing: border-box; margin: 0; padding: 0; }',
'body {',
'  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;',
'  background: #f6f7f9; color: #1f2328; font-size: 14px; line-height: 1.6;',
'}',
'.wrap { max-width: 1080px; margin: 0 auto; padding: 32px 20px 80px; }',
'header { display: flex; align-items: baseline; gap: 12px; margin-bottom: 4px; }',
'h1 { font-size: 20px; font-weight: 600; }',
'.sub { color: #656d76; font-size: 13px; margin-bottom: 24px; }',
'.card { background: #fff; border: 1px solid #d8dee4; border-radius: 10px; padding: 20px; margin-bottom: 16px; }',
'.card h2 { font-size: 15px; font-weight: 600; margin-bottom: 14px; display: flex; justify-content: space-between; align-items: center; }',
'button {',
'  font: inherit; cursor: pointer; border: 1px solid #d8dee4; background: #fff;',
'  padding: 6px 14px; border-radius: 6px; color: #1f2328; transition: .12s;',
'}',
'button:hover { background: #f3f4f6; }',
'button.primary { background: #1f6feb; border-color: #1f6feb; color: #fff; }',
'button.primary:hover { background: #1a5fd0; }',
'button.danger { color: #cf222e; border-color: #ffcecb; }',
'button.danger:hover { background: #fff0ef; }',
'button:disabled { opacity: .5; cursor: not-allowed; }',
'button.sm { padding: 3px 9px; font-size: 12.5px; }',
'table { width: 100%; border-collapse: collapse; }',
'th { text-align: left; font-weight: 500; color: #656d76; font-size: 12.5px; padding: 8px 10px; border-bottom: 1px solid #eaeef2; }',
'td { padding: 11px 10px; border-bottom: 1px solid #f0f3f6; vertical-align: middle; }',
'tr:last-child td { border-bottom: none; }',
'.dot { display: inline-block; width: 7px; height: 7px; border-radius: 50%; margin-right: 6px; }',
'.on { background: #1a7f37; } .off { background: #afb8c1; }',
'.mono { font-family: ui-monospace, SFMono-Regular, Consolas, monospace; font-size: 12.5px; }',
'.url { color: #656d76; word-break: break-all; }',
'.tag { display: inline-block; padding: 1px 7px; border-radius: 20px; font-size: 11.5px; background: #eef1f4; color: #424a53; }',
'.muted { color: #656d76; }',
'.conv { font-size: 12px; color: #424a53; }',
'.stats { font-size: 12px; margin-top: 2px; color: #424a53; }',
'.errtxt { font-size: 12px; color: #a40e15; margin-top: 2px; max-width: 280px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; cursor: help; }',
'.empty { text-align: center; padding: 40px 0; color: #656d76; }',
'label { display: block; font-size: 12.5px; color: #424a53; margin-bottom: 4px; font-weight: 500; }',
'input, select, textarea {',
'  width: 100%; font: inherit; padding: 7px 10px; border: 1px solid #d8dee4;',
'  border-radius: 6px; background: #fff; color: #1f2328;',
'}',
'input:focus, select:focus, textarea:focus { outline: 2px solid #1f6feb33; border-color: #1f6feb; }',
'.grid { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }',
'.field { margin-bottom: 14px; }',
'.hint { font-size: 12px; color: #656d76; margin-top: 4px; }',
'.modal-bg {',
'  position: absolute; inset: 0; background: #00000059; display: flex;',
'  align-items: flex-start; justify-content: center; padding: 40px 16px; overflow: auto;',
'}',
'.modal { background: #fff; border-radius: 12px; width: 100%; max-width: 620px; padding: 24px; }',
'.banner { padding: 10px 14px; border-radius: 8px; margin-bottom: 14px; font-size: 13px; }',
'.warn { background: #fff8e5; border: 1px solid #f0d98a; color: #6b5900; }',
'.err { background: #fff0ef; border: 1px solid #ffcecb; color: #a40e15; }',
'.ok { background: #eaf6ec; border: 1px solid #b7e1c1; color: #0a5c1f; }',
'.actions { display: flex; gap: 6px; justify-content: flex-end; }',
'.right { display: flex; justify-content: flex-end; gap: 8px; margin-top: 18px; }',
'.row { display: flex; gap: 8px; align-items: center; }',
'.spacer { flex: 1; }',
'</style>',
'</head>',
'<body>',
'<div class="wrap" id="app">',
'  <div class="empty">加载中…</div>',
'</div>',
'<script>',
"const $ = (s) => document.querySelector(s);",
"const app = $('#app');",
"let state = { authed: false, initialized: false, storage: 'kv', channels: [], vendors: [], settings: {}, editing: null };",
"",
"async function api(path, opts = {}) {",
"  const res = await fetch('/_admin/api/' + path, {",
"    method: opts.method || 'GET',",
"    headers: opts.body ? { 'Content-Type': 'application/json' } : {},",
"    body: opts.body ? JSON.stringify(opts.body) : undefined,",
"    credentials: 'same-origin',",
"  });",
"  const data = await res.json().catch(() => ({}));",
"  if (res.status === 401) { state.authed = false; state.initialized = data.error !== 'not_initialized'; render(); throw new Error(data.error); }",
"  if (!res.ok && data.error) throw new Error(data.error);",
"  return data;",
"}",
"",
"async function boot() {",
"  try {",
"    const s = await api('session');",
"    state.authed = s.authenticated; state.initialized = s.initialized; state.storage = s.storage;",
"    if (s.authenticated) await reload();",
"    else render();",
"  } catch (e) { render(String(e.message)); }",
"}",
"",
"async function reload() {",
"  const [ch, vd, st] = await Promise.all([api('channels'), api('vendors'), api('settings')]);",
"  state.channels = ch.channels || []; state.vendors = vd.vendors || []; state.settings = st || {};",
"  render();",
"}",
"",
"function esc(s) {",
"  return String(s == null ? '' : s).replace(/[&<>\"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', \"'\": '&#39;' }[c]));",
"}",
"",
"function render(err) {",
"  if (!state.initialized) return renderInit(err);",
"  if (!state.authed) return renderLogin(err);",
"  return renderMain(err);",
"}",
"",
"function renderInit(err) {",
"  app.innerHTML = `",
"    <h1>初始化</h1>",
"    <div class=\"sub\">先设置一个管理员密码，之后用它登录面板。</div>",
"    ${state.storage !== 'kv' ? '<div class=\"banner warn\">当前未绑定 KV，配置无法持久化保存。请先在 wrangler.toml 里配置 kv_namespaces 再部署。</div>' : ''}",
"    ${err ? `<div class=\"banner err\">${esc(err)}</div>` : ''}",
"    <div class=\"card\">",
"      <div class=\"field\"><label>管理员密码（至少 6 位）</label><input id=\"pw\" type=\"password\" autocomplete=\"new-password\"></div>",
"      <div class=\"right\"><button class=\"primary\" id=\"btn\">设置并登录</button></div>",
"    </div>`;",
"  $('#btn').onclick = async () => {",
"    try { await api('init', { method: 'POST', body: { password: $('#pw').value } }); await boot(); }",
"    catch (e) { renderInit(e.message); }",
"  };",
"}",
"",
"function renderLogin(err) {",
"  app.innerHTML = `",
"    <h1>登录</h1>",
"    <div class=\"sub\">cf-api-switch 管理面板</div>",
"    ${err ? `<div class=\"banner err\">${esc(err)}</div>` : ''}",
"    <div class=\"card\">",
"      <div class=\"field\"><label>管理员密码</label><input id=\"pw\" type=\"password\" autocomplete=\"current-password\"></div>",
"      <div class=\"right\"><button class=\"primary\" id=\"btn\">登录</button></div>",
"    </div>`;",
"  $('#btn').onclick = async () => {",
"    try { await api('login', { method: 'POST', body: { password: $('#pw').value } }); await boot(); }",
"    catch (e) { renderLogin(e.message); }",
"  };",
"  $('#pw').onkeydown = (e) => { if (e.key === 'Enter') $('#btn').click(); };",
"}",
"",
"function timeAgo(ts) {",
"  if (!ts) return '从未调用';",
"  const s = Math.floor((Date.now() - ts) / 1000);",
"  if (s < 60) return s + ' 秒前';",
"  if (s < 3600) return Math.floor(s / 60) + ' 分钟前';",
"  if (s < 86400) return Math.floor(s / 3600) + ' 小时前';",
"  return Math.floor(s / 86400) + ' 天前';",
"}",
"",
"function convDesc(c) {",
"  const out = c.protocol === 'responses' ? '新协议 responses' : 'chat/completions';",
"  return '入站 responses / chat / anthropic  →  出站 ' + out;",
"}",
"",
"function renderMain(err) {",
"  const origin = location.origin;",
"  const rows = state.channels.map((c) => {",
"    const st = c.stats || {};",
"    const full = origin + '/' + c.slug + '/v1';",
"    const rate = st.count ? Math.round((st.ok / st.count) * 100) : null;",
"    return `",
"    <tr>",
"      <td><span class=\"dot ${c.enabled ? 'on' : 'off'}\"></span>${c.enabled ? '启用' : '停用'}</td>",
"      <td>",
"        <strong>${esc(c.name)}</strong> <span class=\"tag\">${esc(vendorLabel(c.vendor))}</span>",
"        <div class=\"mono url\">${esc(full)}</div>",
"        <div class=\"row\" style=\"margin-top:4px\">",
"          <button class=\"sm\" data-copy=\"${esc(full)}\">复制地址</button>",
"          <span class=\"muted\">端点：/v1/responses · /v1/chat/completions · /v1/messages</span>",
"        </div>",
"      </td>",
"      <td>",
"        <div class=\"conv\">${esc(convDesc(c))}</div>",
"        ${st.count ? `<div class=\"stats\">请求 ${st.count} · 成功 ${st.ok} · 失败 ${st.fail}${rate !== null ? ' · ' + rate + '%' : ''}</div>`",
"          : '<span class=\"muted\">尚无请求</span>'}",
"        ${st.lastAt ? `<div class=\"muted\">最近: ${timeAgo(st.lastAt)} · ${esc(st.lastModel || '-')} · ${st.lastStatus || '-'}</div>` : ''}",
"        ${st.lastError && st.fail ? `<div class=\"errtxt\" title=\"${esc(st.lastError)}\">⚠ ${esc(st.lastError).slice(0, 40)}${esc(st.lastError).length > 40 ? '…' : ''}</div>` : ''}",
"      </td>",
"      <td><div class=\"actions\">",
"        <button class=\"sm\" data-test=\"${esc(c.id)}\">测试</button>",
"        <button class=\"sm\" data-edit=\"${esc(c.id)}\">编辑</button>",
"        <button class=\"sm\" data-toggle=\"${esc(c.id)}\">${c.enabled ? '停用' : '启用'}</button>",
"        <button class=\"sm danger\" data-del=\"${esc(c.id)}\">删除</button>",
"      </div></td>",
"    </tr>`;",
"  }).join('');",
"",
"  app.innerHTML = `",
"    <header><h1>cf-api-switch</h1><span class=\"tag\">${esc(state.storage === 'kv' ? 'KV 持久化' : '未绑定 KV')}</span></header>",
"    <div class=\"sub\">渠道对外地址：<span class=\"mono\">${esc(origin)}/&lt;渠道名&gt;/v1/responses</span>　·　${state.channels.length} 个渠道</div>",
"    ${state.storage !== 'kv' ? '<div class=\"banner warn\">未绑定 Workers KV，改动只存在于内存，重启即丢失。请在 wrangler.toml 配置 kv_namespaces。</div>' : ''}",
"    ${err ? `<div class=\"banner err\">${esc(err)}</div>` : ''}",
"    <div id=\"msg\"></div>",
"    <div class=\"card\">",
"      <h2>渠道 <button class=\"primary sm\" id=\"add\">+ 新增渠道</button></h2>",
"      ${state.channels.length ? `<table><thead><tr><th>状态</th><th>渠道 / 对外地址</th><th>转化情况</th><th></th></tr></thead><tbody>${rows}</tbody></table>`",
"        : '<div class=\"empty\">还没有渠道。点右上角新增，填入上游地址即可。</div>'}",
"    </div>",
"    <div class=\"card\">",
"      <h2>访问设置</h2>",
"      <div class=\"field\">",
"        <label>客户端 API Key（逗号分隔，留空表示不校验）</label>",
"        <input id=\"keys\" placeholder=\"sk-xxx, sk-yyy\" value=\"${esc((state.settings.clientKeys || []).join(', '))}\">",
"        <div class=\"hint\">配合「要求鉴权」使用。客户端请求需带 Authorization: Bearer &lt;key&gt;</div>",
"      </div>",
"      <label class=\"row\"><input type=\"checkbox\" id=\"reqauth\" ${state.settings.requireAuth ? 'checked' : ''} style=\"width:auto\"> 要求客户端鉴权</label>",
"      <div class=\"right\"><button class=\"primary\" id=\"save-settings\">保存设置</button></div>",
"    </div>",
"    <div class=\"card\">",
"      <h2>管理员</h2>",
"      <div class=\"grid\">",
"        <div class=\"field\"><label>新密码</label><input id=\"newpw\" type=\"password\" autocomplete=\"new-password\"></div>",
"      </div>",
"      <div class=\"right\">",
"        <button id=\"logout\">退出登录</button>",
"        <button class=\"primary\" id=\"chpw\">修改密码</button>",
"      </div>",
"    </div>`,",
"",
"  bindMain();",
"}",
"",
"function vendorLabel(v) {",
"  const found = state.vendors.find((x) => x.name === v);",
"  return found ? found.label : v;",
"}",
"",
"function bindMain() {",
"  $('#add').onclick = () => openEditor(null);",
"  app.querySelectorAll('[data-copy]').forEach((b) => b.onclick = async () => {",
"    try {",
"      await navigator.clipboard.writeText(b.dataset.copy);",
"      const old = b.textContent; b.textContent = '已复制'; b.disabled = true;",
"      setTimeout(() => { b.textContent = old; b.disabled = false; }, 1500);",
"    } catch (e) { prompt('复制失败，请手动复制：', b.dataset.copy); }",
"  });",
"  app.querySelectorAll('[data-edit]').forEach((b) => b.onclick = () => openEditor(state.channels.find((c) => c.id === b.dataset.edit)));",
"  app.querySelectorAll('[data-toggle]').forEach((b) => b.onclick = async () => {",
"    await api('channel/' + b.dataset.toggle + '/toggle', { method: 'POST' }); await reload();",
"  });",
"  app.querySelectorAll('[data-del]').forEach((b) => b.onclick = async () => {",
"    const c = state.channels.find((x) => x.id === b.dataset.del);",
"    if (!confirm('确认删除渠道「' + c.name + '」？此操作不可恢复。')) return;",
"    await api('channel/' + b.dataset.del, { method: 'DELETE' }); await reload();",
"  });",
"  app.querySelectorAll('[data-test]').forEach((b) => b.onclick = async () => {",
"    const id = b.dataset.test; b.disabled = true; const old = b.textContent; b.textContent = '测试中…';",
"    try {",
"      const r = await api('channel/' + id + '/test', { method: 'POST' });",
"      banner(r.ok ? 'ok' : 'err', (r.ok ? '✓ ' : '✗ ') + r.message + '（HTTP ' + r.status + ' · ' + r.latency + 'ms）');",
"    } catch (e) { banner('err', e.message); }",
"    b.textContent = old; b.disabled = false;",
"  });",
"  $('#save-settings').onclick = async () => {",
"    const keys = $('#keys').value.split(',').map((s) => s.trim()).filter(Boolean);",
"    await api('settings', { method: 'POST', body: { clientKeys: keys, requireAuth: $('#reqauth').checked } });",
"    banner('ok', '访问设置已保存');",
"  };",
"  $('#chpw').onclick = async () => {",
"    const pw = $('#newpw').value;",
"    if (pw.length < 6) return banner('err', '密码至少 6 位');",
"    await api('password', { method: 'POST', body: { password: pw } });",
"    $('#newpw').value = ''; banner('ok', '密码已更新');",
"  };",
"  $('#logout').onclick = async () => { await api('logout', { method: 'POST' }); state.authed = false; render(); };",
"}",
"",
"function banner(kind, text) {",
"  const el = $('#msg');",
"  if (!el) return;",
"  el.innerHTML = '<div class=\"banner ' + kind + '\">' + esc(text) + '</div>';",
"  setTimeout(() => { if (el.innerHTML.includes(text)) el.innerHTML = ''; }, 6000);",
"}",
"",
"function openEditor(channel) {",
"  const c = channel || { name: '', slug: '', baseUrl: '', apiKey: '', vendor: 'generic', protocol: 'openai-chat', models: [], weight: 100, timeoutMs: 120000, enabled: true, apiVersion: undefined, dropParams: [], headers: {} };",
"  const opts = state.vendors.map((v) => '<option value=\"' + v.name + '\" label=\"' + v.label + '\"></option>').join('');",
"  const bg = document.createElement('div');",
"  bg.className = 'modal-bg';",
"  bg.innerHTML = `",
"    <div class=\"modal\">",
"      <h2 style=\"margin-bottom:18px\">${channel ? '编辑渠道' : '新增渠道'}</h2>",
"      <div class=\"grid\">",
"        <div class=\"field\"><label>渠道名称</label><input id=\"f-name\" value=\"${esc(c.name)}\" placeholder=\"DeepSeek 官方\"></div>",
"        <div class=\"field\"><label>路径标识（英文，用于 URL）</label><input id=\"f-slug\" value=\"${esc(c.slug)}\" placeholder=\"deepseek\"></div>",
"      </div>",
"      <div class=\"field\">",
"        <label>上游地址</label><input id=\"f-base\" value=\"${esc(c.baseUrl)}\" placeholder=\"https://api.deepseek.com\">",
"        <div class=\"hint\" id=\"basehint\">填到版本号之前即可，/v1 可带可不带。火山方舟请填到 /api/v3</div>",
"      </div>",
"      <div class=\"field\"><label>API Key</label><input id=\"f-key\" value=\"\" placeholder=\"${esc(c.apiKey ? '已保存（' + c.apiKey + '），留空表示不修改' : 'sk-xxx')}\"></div>",
"      <div class=\"grid\">",
"        <div class=\"field\"><label>厂商（可自由填写，预设仅供参考）</label>",
"          <input id=\"f-vendor\" list=\"vendor-list\" value=\"${esc(c.vendor)}\" placeholder=\"deepseek / ark / 任意名字\">",
"          <datalist id=\"vendor-list\">${opts}</datalist>",
"          <div class=\"hint\" id=\"vhint\"></div></div>",
"        <div class=\"field\"><label>上游协议</label><select id=\"f-proto\">",
"          <option value=\"openai-chat\"${c.protocol === 'openai-chat' ? ' selected' : ''}>chat/completions</option>",
"          <option value=\"responses\"${c.protocol === 'responses' ? ' selected' : ''}>新协议 responses</option>",
"        </select></div>",
"      </div>",
"      <details style=\"margin-bottom:14px\">",
"        <summary style=\"cursor:pointer;color:#424a53;font-size:13px\">高级：URL 版本段 / 剔除参数 / 自定义请求头</summary>",
"        <div style=\"padding-top:12px\">",
"          <div class=\"grid\">",
"            <div class=\"field\"><label>URL 版本段</label>",
"              <input id=\"f-apiver\" value=\"${esc(c.apiVersion === '' ? '' : (c.apiVersion ?? 'v1'))}\" placeholder=\"v1\">",
"              <div class=\"hint\">拼在地址与端点之间。默认 v1；上游地址已自带版本号时勾选下方选项</div></div>",
"            <div class=\"field\"><label>剔除参数</label>",
"              <input id=\"f-drop\" value=\"${esc((c.dropParams || []).join(', '))}\" placeholder=\"user, stream_options, logit_bias\">",
"              <div class=\"hint\">逗号分隔。上游不认的字段填这里，发送前会被删掉</div></div>",
"          </div>",
"          <label class=\"row\" style=\"margin-bottom:12px\"><input type=\"checkbox\" id=\"f-nover\" ${c.apiVersion === '' ? 'checked' : ''} style=\"width:auto\"> 上游地址已含版本号，不再拼接（火山方舟这类）</label>",
"          <div class=\"field\"><label>自定义请求头（JSON 对象）</label>",
"            <textarea id=\"f-headers\" rows=\"2\" placeholder='{\"x-api-key\": \"xxx\"}'>${esc(Object.keys(c.headers || {}).length ? JSON.stringify(c.headers) : '')}</textarea></div>",
"        </div>",
"      </details>",
"      <div class=\"field\">",
"        <label>模型白名单（逗号分隔，留空表示不限制）</label>",
"        <textarea id=\"f-models\" rows=\"2\" placeholder=\"deepseek-chat, deepseek-reasoner\">${esc((c.models || []).join(', '))}</textarea>",
"        <div class=\"right\" style=\"margin-top:6px\"><button class=\"sm\" id=\"fetch-models\">从上游拉取</button></div>",
"      </div>",
"      <div class=\"grid\">",
"        <div class=\"field\"><label>权重（同模型多渠道时，大的优先）</label><input id=\"f-weight\" type=\"number\" value=\"${c.weight}\"></div>",
"        <div class=\"field\"><label>超时（毫秒）</label><input id=\"f-timeout\" type=\"number\" value=\"${c.timeoutMs}\"></div>",
"      </div>",
"      <label class=\"row\" style=\"margin-bottom:8px\"><input type=\"checkbox\" id=\"f-enabled\" ${c.enabled ? 'checked' : ''} style=\"width:auto\"> 启用该渠道</label>",
"      <div class=\"right\">",
"        <button id=\"cancel\">取消</button>",
"        <button class=\"sm\" id=\"test-now\">测试连通</button>",
"        <button class=\"primary\" id=\"save\">保存</button>",
"      </div>",
"    </div>`;",
"  document.body.appendChild(bg);",
"",
"  const vhint = () => {",
"    const name = bg.querySelector('#f-vendor').value.trim().toLowerCase();",
"    const v = state.vendors.find((x) => x.name === name);",
"    bg.querySelector('#vhint').textContent = !name",
"      ? '留空按通用 OpenAI 兼容处理'",
"      : v ? v.hint + '　建议填：' + v.basePlaceholder",
"      : '自定义厂商，按通用 OpenAI 兼容处理。差异用下面「高级」里的版本段和剔除参数调整';",
"  };",
"  bg.querySelector('#f-vendor').oninput = vhint; vhint();",
"  bg.querySelector('#cancel').onclick = () => bg.remove();",
"  bg.onclick = (e) => { if (e.target === bg) bg.remove(); };",
"",
"  bg.querySelector('#save').onclick = async () => {",
"    const payload = {",
"      id: c.id,",
"      name: bg.querySelector('#f-name').value.trim(),",
"      slug: bg.querySelector('#f-slug').value.trim(),",
"      baseUrl: bg.querySelector('#f-base').value.trim(),",
"      vendor: bg.querySelector('#f-vendor').value,",
"      protocol: bg.querySelector('#f-proto').value,",
"      models: bg.querySelector('#f-models').value.split(',').map((s) => s.trim()).filter(Boolean),",
"      weight: Number(bg.querySelector('#f-weight').value) || 100,",
"      timeoutMs: Number(bg.querySelector('#f-timeout').value) || 120000,",
"      enabled: bg.querySelector('#f-enabled').checked,",
"      apiVersion: bg.querySelector('#f-nover').checked ? '' : (bg.querySelector('#f-apiver').value.trim() || undefined),",
"      dropParams: bg.querySelector('#f-drop').value.split(',').map((s) => s.trim()).filter(Boolean),",
"    };",
"    const hdrRaw = bg.querySelector('#f-headers').value.trim();",
"    if (hdrRaw) {",
"      try { payload.headers = JSON.parse(hdrRaw); }",
"      catch (e) { alert('自定义请求头不是合法 JSON：' + e.message); return; }",
"    }",
"    const key = bg.querySelector('#f-key').value.trim();",
"    if (key) payload.apiKey = key;",
"    else if (c.apiKey) payload.apiKey = c.apiKey;",
"    try {",
"      await api('channels', { method: 'POST', body: payload });",
"      bg.remove(); await reload();",
"    } catch (e) { alert(e.message); }",
"  };",
"",
"  // 测试连通 / 拉取模型都不依赖已保存状态：直接从表单取值探测",
"  const probeBody = () => {",
"    const body = {};",
"    if (c.id) body.id = c.id;",
"    const base = bg.querySelector('#f-base').value.trim();",
"    if (base) body.baseUrl = base;",
"    const vendor = bg.querySelector('#f-vendor').value.trim();",
"    if (vendor) body.vendor = vendor;",
"    body.apiVersion = bg.querySelector('#f-nover').checked ? '' : (bg.querySelector('#f-apiver').value.trim() || undefined);",
"    const key = bg.querySelector('#f-key').value.trim();",
"    if (key) body.apiKey = key;",
"    return body;",
"  };",
"",
"  bg.querySelector('#test-now').onclick = async () => {",
"    const b = bg.querySelector('#test-now'); b.disabled = true; b.textContent = '测试中…';",
"    try {",
"      const r = await api('probe/test', { method: 'POST', body: probeBody() });",
"      alert((r.ok ? '✓ ' : '✗ ') + r.message + '\\nHTTP ' + r.status + ' · ' + r.latency + 'ms');",
"    } catch (e) { alert(e.message); }",
"    b.textContent = '测试连通'; b.disabled = false;",
"  };",
"",
"  bg.querySelector('#fetch-models').onclick = async () => {",
"    const b = bg.querySelector('#fetch-models'); b.disabled = true; b.textContent = '拉取中…';",
"    try {",
"      const r = await api('probe/models', { method: 'POST', body: probeBody() });",
"      if (r.ok) { bg.querySelector('#f-models').value = r.models.join(', '); b.textContent = '已填充 ' + r.models.length + ' 个'; }",
"      else { alert(r.message); b.textContent = '从上游拉取'; }",
"    } catch (e) { alert(e.message); b.textContent = '从上游拉取'; }",
"    b.disabled = false;",
"  };",
"}",
"",
"boot();",
'</script>',
'</body>',
'</html>',
].join('\n');
